transformer:
	gcc -o transformer main.cpp ../PCD-Viewer/pcd_helpers.cpp -I/usr/include/pcl-1.8 -I/usr/include/eigen3 -I/usr/include/vtk/ -std=c++11 -lboost_system -lboost_filesystem -lpcl_io -lpcl_common -lpcl_filters -lstdc++ -lm
