grabber_opencv2:
	gcc -o grabber main.cpp -std=c++11 -lfreenect2 -lboost_system -lboost_filesystem -lboost_date_time -lopencv_core -lopencv_highgui -lstdc++
grabber_opencv3:
	gcc -o grabber main.cpp -std=c++11 -lfreenect2 -lboost_system -lboost_filesystem -lboost_date_time -lopencv_core -lopencv_imgcodecs -lstdc++
