viewer:
	gcc -o viewer main.cpp pcd_helpers.cpp -I/usr/include/pcl-1.8 -I/usr/include/eigen3 -I/usr/include/vtk/ -std=c++11 -lboost_system -lboost_filesystem -lvtkCommonDataModel -lvtkCommonMath -lvtkCommonCore -lvtkRenderingCore -lpcl_io -lpcl_visualization -lpcl_common
